### PR TITLE
python-lsp-server 1.3.3

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/python-lsp/python-lsp-server/blob/v1.3.3/CHANGELOG.md
License: https://github.com/python-lsp/python-lsp-server/blob/v1.3.3/LICENSE
Requirements: https://github.com/python-lsp/python-lsp-server/blob/v1.3.3/setup.py

Actions:
1. Add missing setuptools and wheel
2. Fix python in host
3. Update pinnings for run dependencies
4. Add test/imports
5. Add doc_url

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
After running the command `conda create -n test_env --dry-run python=3.10 pip setuptools wheel "autopep8 >=1.6.0,<1.7.0" "flake8 >=4.0.0,<4.1.0" "jedi >=0.17.2,<0.19.0" "mccabe >=0.6.0,<0.7.0" pluggy "python-lsp-jsonrpc >=1.0.0" "pycodestyle >=2.8.0,<2.9.0" "pydocstyle >=2.0.0" "pyflakes >=2.4.0,<2.5.0" "pylint >=2.5.0" "rope >=0.10.5" "ujson >=3.0.0" yapf -vvv 2>&1 | grep -e "-> 0"`
an output is:
```
DEBUG conda.resolve:filter_group(635): astroid: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): astroid: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): astroid: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): astroid: pruned from 114 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 30 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): astroid: pruned from 114 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 30 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): astroid: pruned from 114 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 30 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 1 -> 0
```
pylint  haven't python 3.10 support so we need to rebuild or update it

**Comment by skupr-anaconda** [comment]
I've fixed pylint 2.12.2

**Comment by skupr-anaconda** [comment]
After running the command `conda create -n test_env --dry-run python=3.10 pip setuptools wheel "autopep8 >=1.6.0,<1.7.0" "flake8 >=4.0.0,<4.1.0" "jedi >=0.17.2,<0.19.0" "mccabe >=0.6.0,<0.7.0" pluggy "python-lsp-jsonrpc >=1.0.0" "pycodestyle >=2.8.0,<2.9.0" "pydocstyle >=2.0.0" "pyflakes >=2.4.0,<2.5.0" "pylint >=2.5.0" "rope >=0.10.5" "ujson >=3.0.0" yapf -vvv 2>&1 | grep -e "-> 0"`:

```
DEBUG conda.resolve:filter_group(635): python: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): rope: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): python-lsp-jsonrpc: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): pyflakes: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pydocstyle: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pycodestyle: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): mccabe: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): jedi: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): autopep8: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): yapf: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): wheel: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): setuptools: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): pluggy: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): pip: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): ujson: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): python: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): rope: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): python-lsp-jsonrpc: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): pyflakes: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pydocstyle: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pycodestyle: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): mccabe: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): jedi: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): autopep8: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): yapf: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): wheel: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): setuptools: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): pluggy: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): pip: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): ujson: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): python: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): rope: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): python-lsp-jsonrpc: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): pyflakes: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pydocstyle: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pycodestyle: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): mccabe: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): jedi: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): autopep8: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): yapf: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): wheel: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): setuptools: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): pluggy: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): pip: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): ujson: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): python: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): rope: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): python-lsp-jsonrpc: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pylint: pruned from 8 -> 0
DEBUG conda.resolve:filter_group(635): pyflakes: pruned from 6 -> 0
DEBUG conda.resolve:filter_group(635): pydocstyle: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): pycodestyle: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): mccabe: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): jedi: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): autopep8: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): yapf: pruned from 1 -> 0
DEBUG conda.resolve:filter_group(635): wheel: pruned from 4 -> 0
DEBUG conda.resolve:filter_group(635): setuptools: pruned from 5 -> 0
DEBUG conda.resolve:filter_group(635): pluggy: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): pip: pruned from 3 -> 0
DEBUG conda.resolve:filter_group(635): ujson: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
```

**Comment by skupr-anaconda** [comment]
pluggy 1.0.0 haven't python 3.10 support. We should rebuild it

**Comment by skupr-anaconda** [comment]
ujson 4.2.0 haven't python 3.10 support. We should rebuild it

**Comment by skupr-anaconda** [comment]
`conda create -n test_env --dry-run python=3.10 pip setuptools wheel "autopep8 >=1.6.0,<1.7.0" "flake8 >=4.0.0,<4.1.0" "jedi >=0.17.2,<0.19.0" "mccabe >=0.6.0,<0.7.0" pluggy "python-lsp-jsonrpc >=1.0.0" "pycodestyle >=2.8.0,<2.9.0" "pydocstyle >=2.0.0" "pyflakes >=2.4.0,<2.5.0" "pylint >=2.5.0" "rope >=0.10.5" "ujson >=3.0.0" yapf -vvv 2>&1 | grep -e "-> 0"`
```
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 2 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
DEBUG conda.resolve:filter_group(635): flake8: pruned from 7 -> 0
```

Flake8 4.0.1 hasn't python 3.10 support. We need to rebuild it

**Comment by skupr-anaconda** [comment]
I've fixed flake8 4.0.1 and it's now with python 3.10 support

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
